// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Pos5.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Pos5::Pos5(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::controlSS.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void Pos5::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void Pos5::Execute() {
	Robot::controlSS->setPos5();
}

// Make this return true when this Command no longer needs to run execute()
bool Pos5::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void Pos5::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Pos5::Interrupted() {

}
